syntax = "proto3";

package config;

message Ai {
  AiMode ai_mode = 1;
  string policy_name = 2;
  string pretrained_model_path = 3;
  uint32 node_id = 4;
  repeated string subscribe_topics = 5;
  repeated string publish_topics = 6;
  oneof policy_config {
    ExamplePolicyConfig example_policy_config = 7;
  }
}

enum AiMode {
  MODE_INVALID = 0;
  MODE_TRAINING = 1;
  MODE_INFERENCE = 2;
  MODE_MOCK_INFERENCE = 3; // TODO: Remove this.
}

message ExamplePolicyConfig {
  int32 hidden_size = 1;
  int32 n_layer = 2;
  int32 n_head = 3;
  string activation_function = 4;
  double dropout = 5;
  int32 n_inner = 6;
  int32 context_length = 7;
  int32 vision_embedding_dim = 8;
}

