load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "pybricks_ble_transport_py",
    srcs = ["pybricks_ble_transport.py"],
)
