general {
  operation_mode: MODE_TRAINING
  name: "ant"
}
ai {
  training {
    environment: TRAINING_ENV_SIMULATION
    method: TRAINING_METHOD_RL
    simulator_backend: SIM_BACKEND_ISAAC_SIM
    rl {
      task: "ant"
      algorithm: "skrl"
      max_iterations: 100
      num_envs: 1000
      save_path: "ant_isaac_skrl_ppo"
      render: false
    }
  }  
}
