general {
  operation_mode: MODE_TRAINING
  name: "ant"
}
ai {
  training {
    environment: TRAINING_ENV_SIMULATION
    method: TRAINING_METHOD_RL
    model_path: "simulation/models/ant.xml"
    simulator_backend: SIM_BACKEND_MJX
    rl {
      task: "ant"
      frame_skip: 5
      algorithm: "mjx_ppo"
      max_iterations: 500
      num_envs: 1000
      save_path: "ant_mjx_ppo"
    }
  }
}
