filegroup(
    name = "config_presets",
    srcs = [
        "so100_with_example_ai.pbtxt",
        "so100_with_follower.pbtxt",
        "two_so100_encoder_test.pbtxt",
        "camera_test.pbtxt",
        ],
    visibility = ["//visibility:public"],
)