general{
    operation_mode: MODE_TEST
  }
  
  robot {
    name: "lds01_lidar_test"
    id: 1
  
    perceptions {
      single_perceptions {
        node_id: 1
        publish_topic: "lds01_lidar_1"
        perception_type: LIDAR
        publish_rate_hz: 3
        lidar {
          lidar_name: "lds01_lidar_1"
          id: 1
          lidar_type: LDS01
          comm {
            comm_type: SERIAL
            serial_config {
              id: 1
              port: "/dev/ttyUSB1"
              baudrate: 230400
            }
          }          
        }
      }
    }
  }
