general{
  operation_mode: MODE_TEST
}

robot {
  name: "camera_test"
  id: 1
  robot_type: MANIPULATOR_ARM

  perceptions {
    single_perceptions {
      node_id: 1
      publish_topic: "camera_1"
      perception_type: CAMERA
      publish_rate_hz: 30
      camera {
        camera_name: "webcam"
        id: 1
        camera_type: OPENCV
        comm{}
        opencv_config {
          id: 0
          width: 640
          height: 480
          fps: 30
        }
      }
    }
  }
}
