general{
  operation_mode: MODE_DATA_STORE
}

ai {
  data_stores {
    single_data_stores {
      node {
        id: 1
        node_type: DATA_STORE
        qos_setting {}
      }
      store_path: "/tmp/Joshua/data/sample_recordings"
      data_store_mode: LOCAL_FILE
      data_store_type: HUGGING_FACE_DATASET
      data_infos {
        ros2_data_type: IMAGE
        topic: "camera_1"
      }
      data_infos {
        ros2_data_type: FLOAT32
        topic: "sts3215_encoder_1"
      }
      data_infos {
        ros2_data_type: FLOAT32
        topic: "sts3215_encoder_2"
      }
      data_infos {
        ros2_data_type: FLOAT32
        topic: "sts3215_encoder_3"
      }
      data_infos {
        ros2_data_type: FLOAT32
        topic: "sts3215_encoder_4"
      }
      data_infos {
        ros2_data_type: FLOAT32
        topic: "sts3215_encoder_5"
      }
      data_infos {
        ros2_data_type: FLOAT32
        topic: "sts3215_encoder_6"
      }
  }
}
}
