general{
  operation_mode: MODE_MOCK_INFERENCE
}
robot {
  name: "so100"
  id: 1
  robot_type: MANIPULATOR_ARM

  actions {
    single_actions {
      node_id: 1
      subscribe_topic: "mock_action_1"
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_1"
        id: 1
        actuator_type: STS3215_SERVO
        comm {
          comm_type: SERIAL
          serial_config {
            id: 1
            port: "/dev/ttyACM0"
            baudrate: 1000000
          }
        }
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 973
        operational_upper_limit: 3034
        encoder_data_mode: ENCODER_DATA_MODE_NORMALIZED_MINUS_ONE_TO_ONE
        sts3215_config {
          servo_id: 1
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 2070
        }
      }
    }
    single_actions {
      node_id: 1
      subscribe_topic: "mock_action_2"
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_2"
        id: 2
        actuator_type: STS3215_SERVO
        comm {
          comm_type: SERIAL
          serial_config {
            id: 2
            port: "/dev/ttyACM0"
            baudrate: 1000000
          }
        }
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 858
        operational_upper_limit: 3154
        encoder_data_mode: ENCODER_DATA_MODE_NORMALIZED_MINUS_ONE_TO_ONE
        sts3215_config {
          servo_id: 2
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 847
        }
      }
    }
    single_actions {
      node_id: 1
      subscribe_topic: "mock_action_3"
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_3"
        id: 3
        actuator_type: STS3215_SERVO
        comm {
          comm_type: SERIAL
          serial_config {
            id: 3
            port: "/dev/ttyACM0"
            baudrate: 1000000
          }
        }
        physical_lower_limit: 0
         physical_upper_limit: 4095
        operational_lower_limit: 798
        operational_upper_limit: 3015
        encoder_data_mode: ENCODER_DATA_MODE_NORMALIZED_MINUS_ONE_TO_ONE
        sts3215_config {
          servo_id: 3
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 3011
        }
      }
    }
    single_actions {
      node_id: 1
      subscribe_topic: "mock_action_4"
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_4"
        id: 4
        actuator_type: STS3215_SERVO
        comm {
          comm_type: SERIAL
          serial_config {
            id: 4
            port: "/dev/ttyACM0"
            baudrate: 1000000
          }
        }
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 668
        operational_upper_limit: 3124
        encoder_data_mode: ENCODER_DATA_MODE_NORMALIZED_MINUS_ONE_TO_ONE
        sts3215_config {
          servo_id: 4
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 655
        }
      }
    }
    single_actions {
      node_id: 1
      subscribe_topic: "mock_action_5"
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_5"
        id: 5
        actuator_type: STS3215_SERVO
        comm {
          comm_type: SERIAL
          serial_config {
            id: 5
            port: "/dev/ttyACM0"
            baudrate: 1000000
          }
        }
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 902
        operational_upper_limit: 2955
        encoder_data_mode: ENCODER_DATA_MODE_NORMALIZED_MINUS_ONE_TO_ONE
        sts3215_config {
          servo_id: 5
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 1838
        }
      }
    }
    single_actions {
      node_id: 1
      subscribe_topic: "mock_action_6"
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_6"
        id: 6
        actuator_type: STS3215_SERVO
        comm {
          comm_type: SERIAL
          serial_config {
            id: 6
            port: "/dev/ttyACM0"
            baudrate: 1000000
          }
        }
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 1795
        operational_upper_limit: 3235
        encoder_data_mode: ENCODER_DATA_MODE_NORMALIZED_MINUS_ONE_TO_ONE
        sts3215_config {
          servo_id: 6
          move_time_in_ms: 40
          move_speed: 2200
          idle_position: 1806
        }
      }
    }
  }

  perceptions {
    single_perceptions {
      node_id: 2
      publish_topic: "camera_1"
      perception_type: CAMERA
      publish_rate_hz: 30
      camera {
        camera_name: "webcam"
        id: 1
        camera_type: OPENCV
        comm{}
        opencv_config {
          id: 0
          width: 640
          height: 480
          fps: 30
        }
      }
    }
  }
}

ai {
  models {
    single_model {
      policy_name: "example_policy"
      node_id: 3

      subscriptions {
        ros2_data_type: IMAGE
        topic: "camera_1"
      }

      pubishers {
        ros2_data_type: FLOAT32
        topic: "mock_action_1"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "mock_action_2"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "mock_action_3"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "mock_action_4"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "mock_action_5"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "mock_action_6"
      }

      example_policy_config {
        hidden_size: 256
        n_layer: 4
        n_head: 4
        activation_function: "relu"
        dropout: 0.1
        n_inner: 1024
        context_length: 20
        vision_embedding_dim: 128
      }
    }
  }
}
