base: "so100_mock_inference.pbtxt"

general{
  operation_mode: MODE_INFERENCE
}


ai {
  models {
    single_model {
      policy_name: "smolvla_policy"
      pretrained_model_path: "lerobot/smolvla_base"
      node_id: 3

      subscriptions {
        ros2_data_type: IMAGE
        topic: "camera_1"
      }

      pubishers {
        ros2_data_type: FLOAT32
        topic: "smolvla_action_1"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "smolvla_action_2"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "smolvla_action_3"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "smolvla_action_4"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "smolvla_action_5"
      }
      pubishers {
        ros2_data_type: FLOAT32
        topic: "smolvla_action_6"
      }

    }
  }
}