robot {
  name: "so100"
  id: 1
  trigger_frequency: 10
  robot_type: MANIPULATOR_ARM

  actuations {
    single_actuation {
      actuator {
        actuator_name: "sts_motor_1"
        id: 1
        actuation_type: STS3215
        comm_type: SERIAL
        serial_config {
          id: 1
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_config {
          id: 1
          physical_lower_limit: 0
          physical_upper_limit: 4095
          operational_lower_limit: 1024
          operational_upper_limit: 3072
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 2070
        }
      }
    }
    single_actuation {
      actuator {
        actuator_name: "sts_motor_2"
        id: 2
        actuation_type: STS3215
        comm_type: SERIAL
        serial_config {
          id: 2
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_config {
          id: 2
          physical_lower_limit: 0
          physical_upper_limit: 4095
          operational_lower_limit: 800
          operational_upper_limit: 3000
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 847
        }
      }
    }
    single_actuation {
      actuator {
        actuator_name: "sts_motor_3"
        id: 3
        actuation_type: STS3215
        comm_type: SERIAL
        serial_config {
          id: 3
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_config {
          id: 3
          physical_lower_limit: 0
          physical_upper_limit: 4095
          operational_lower_limit: 950
          operational_upper_limit: 3000
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 3011
        }
      }
    }
    single_actuation {
      actuator {
        actuator_name: "sts_motor_4"
        id: 4
        actuation_type: STS3215
        comm_type: SERIAL
        serial_config {
          id: 4
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_config {
          id: 4
          physical_lower_limit: 0
          physical_upper_limit: 4095
          operational_lower_limit: 900
          operational_upper_limit: 3072
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 655
        }
      }
    }
    single_actuation {
      actuator {
        actuator_name: "sts_motor_5"
        id: 5
        actuation_type: STS3215
        comm_type: SERIAL
        serial_config {
          id: 5
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_config {
          id: 5
          physical_lower_limit: 0
          physical_upper_limit: 4095
          operational_lower_limit: 10
          operational_upper_limit: 3000
          move_time_in_ms: 40
          move_speed: 1500
          idle_position: 1838
        }
      }
    }
    single_actuation {
      actuator {
        actuator_name: "sts_motor_6"
        id: 6
        actuation_type: STS3215
        comm_type: SERIAL
        serial_config {
          id: 6
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_config {
          id: 6
          physical_lower_limit: 0
          physical_upper_limit: 4095
          operational_lower_limit: 1762
          operational_upper_limit: 2400
          move_time_in_ms: 40
          move_speed: 2200
          idle_position: 1806
        }
      }
    }
  }

  perceptions {
    single_perception {
      sensor {
        sensor_name: "webcam"
        id: 1
        sensor_type: CAMERA
        comm_type: COMM_INVALID
        camera_config {
          id: 1
        }
      }
    }
    single_perception {
      sensor {
        sensor_name: "sts3215_encoder_1"
        id: 2
        sensor_type: ENCODER
        comm_type: SERIAL
        serial_config {
          id: 1
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_encoder_config {
          id: 1
        }
      }
    }
    single_perception {
      sensor {
        sensor_name: "sts3215_encoder_2"
        id: 2
        sensor_type: ENCODER
        comm_type: SERIAL
        serial_config {
          id: 2
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_encoder_config {
          id: 2
        }
      }
    }
    single_perception {
      sensor {
        sensor_name: "sts3215_encoder_3"
        id: 2
        sensor_type: ENCODER
        comm_type: SERIAL
        serial_config {
          id: 3
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_encoder_config {
          id: 3
        }
      }
    }
    single_perception {
      sensor {
        sensor_name: "sts3215_encoder_4"
        id: 4
        sensor_type: ENCODER
        comm_type: SERIAL
        serial_config {
          id: 4
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_encoder_config {
          id: 4
        }
      }
    }
    single_perception {
      sensor {
        sensor_name: "sts3215_encoder_5"
        id: 5
        sensor_type: ENCODER
        comm_type: SERIAL
        serial_config {
          id: 5
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_encoder_config {
          id: 5
        }
      }
    }
    single_perception {
      sensor {
        sensor_name: "sts3215_encoder_6"
        id: 6
        sensor_type: ENCODER
        comm_type: SERIAL
        serial_config {
          id: 6
          port: "/dev/ttyACM0"
          baudrate: 1000000
        }
        sts3215_encoder_config {
          id: 6
        }
      }
    }
  }
}

ai {
  policy_name: "decision_transformer"
  decision_transformer_config {
    hidden_size: 256
    n_layer: 4
    n_head: 4
    activation_function: "relu"
    dropout: 0.1
    n_inner: 1024
    context_length: 20
    vision_embedding_dim: 128
  }
}