general {
  operation_mode: MODE_TRAINING
  robot_type: ROBOT_TYPE_MANIPULATOR_ARM
  name: "so100"
}
ai {
  training {
    environment: TRAINING_ENV_SIMULATION
    method: TRAINING_METHOD_RL
    model_path: "simulation/models/so_arm100_pick_place.xml"
    rl {
      task: "pick_place"
      frame_skip: 10
      algorithm: "ppo"
      total_timesteps: 500000
      num_eval_episodes: 10
      save_path: "pick_place_ppo"
      render: true
      num_envs: 8
    }
  }
}
