general {
  operation_mode: MODE_TRAINING
  name: "trileg"
}
ai {
  training {
    environment: TRAINING_ENV_SIMULATION
    method: TRAINING_METHOD_RL
    simulator_backend: SIM_BACKEND_ISAAC_SIM
    rl {
      task: "trileg"
      algorithm: "skrl"
      max_iterations: 500
      num_envs: 4096
      save_path: "trileg_isaac_skrl_ppo"
      render: false
    }
  }
}
