repos:
  - repo: local
    hooks:
      - id: lint-check
        name: Lint & Format Checks
        entry: hooks/lint_check.sh
        language: system
        stages: [pre-push]
        pass_filenames: false
