module(
    name = "ubirobotics",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.1.1")
bazel_dep(name = "rules_python", version = "0.40.0")
bazel_dep(name = "rules_proto", version = "7.0.2")
bazel_dep(name = "protobuf", version = "29.0")
bazel_dep(name = "pybind11_bazel", version = "2.13.6")
bazel_dep(name = "boost.asio", version = "1.87.0")
bazel_dep(name = "gflags", version = "2.2.2")
bazel_dep(name = "glog", version = "0.7.1")
# bazel_dep(name = "libevdev", version = "1.13.2") # This is for xbox controller but deprecated.

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.10",
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "ubirobotics_pip_deps",
    python_version = "3.10",
    requirements_lock = "//:requirements.txt",
)
use_repo(pip, "ubirobotics_pip_deps")

# Custom rule for system dependencies
system_libs = use_repo_rule("//:system_deps.bzl", "system_libs_repo")
system_libs(name = "local_deps")