def _ros2_libs_repo_impl(ctx):
    """Implementation of the ros2_libs_repo rule."""
    
    build_content = """
# AUTOGENERATED by ros2_libs_repo rule
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# Platform selectors for x86_64 vs aarch64
config_setting(
    name = "cpu_x86_64",
    constraint_values = ["@platforms//cpu:x86_64"],
)

config_setting(
    name = "cpu_aarch64",
    constraint_values = ["@platforms//cpu:aarch64"],
)

# =============================================================================
# ROS2 System Libraries with Cross-Compilation Support
# =============================================================================

# ROS2 Core Libraries
cc_library(
    name = "rclcpp",
    hdrs = glob([
        "opt/ros/humble/include/rclcpp/**/*.h",
        "opt/ros/humble/include/rclcpp/**/*.hpp",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rclcpp",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrclcpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrclcpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrclcpp",
        ],
    }),
    deps = [
        ":rcl",
        ":rcpputils",
        ":rcutils",
        ":rmw",
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
        ":rosidl_typesupport_c",
        ":builtin_interfaces",
        ":rcl_interfaces",
        ":tracetools",
        ":libstatistics_collector",
        ":rosgraph_msgs",
        ":ament_index_cpp",
    ],
)

cc_library(
    name = "ament_index_cpp",
    hdrs = glob([
        "opt/ros/humble/include/ament_index_cpp/**/*.hpp",
        "opt/ros/humble/include/ament_index_cpp/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/ament_index_cpp",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lament_index_cpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lament_index_cpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lament_index_cpp",
        ],
    }),
)

cc_library(
    name = "rcl",
    hdrs = glob([
        "opt/ros/humble/include/rcl/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rcl",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrcl",
        ],
    }),
    deps = [
        ":rcutils",
        ":rmw",
        ":rosidl_runtime_c",
        ":rcl_yaml_param_parser",
        ":rmw_implementation",
        ":rcl_logging_interface",
    ],
)

cc_library(
    name = "rcl_logging_interface",
    hdrs = glob([
        "opt/ros/humble/include/rcl_logging_interface/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rcl_logging_interface",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_logging_interface",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_logging_interface",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrcl_logging_interface",
        ],
    }),
    deps = [
        ":rcutils",
        ":rcl_logging_spdlog",
    ],
)

cc_library(
    name = "rcl_logging_spdlog",
    hdrs = glob([
        "opt/ros/humble/include/rcl_logging_spdlog/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rcl_logging_spdlog",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_logging_spdlog",
            "-lspdlog",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_logging_spdlog",
            "-lspdlog",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrcl_logging_spdlog",
            "-lspdlog",
        ],
    }),
    deps = [":rcutils", ":spdlog_vendor"],
)

cc_library(
    name = "spdlog_vendor",
    linkopts = ["-lspdlog"],
)

cc_library(
    name = "rmw_implementation",
    hdrs = glob([
        "opt/ros/humble/include/rmw_implementation/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rmw_implementation",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrmw_implementation",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrmw_implementation",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrmw_implementation",
        ],
    }),
    deps = [
        ":rmw",
        ":rcutils",
        ":rosidl_runtime_c",
    ],
)

cc_library(
    name = "rcl_yaml_param_parser",
    hdrs = glob([
        "opt/ros/humble/include/rcl_yaml_param_parser/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rcl_yaml_param_parser",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_yaml_param_parser",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_yaml_param_parser",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrcl_yaml_param_parser",
        ],
    }),
)

cc_library(
    name = "rcpputils",
    hdrs = glob([
        "opt/ros/humble/include/rcpputils/**/*.hpp",
        "opt/ros/humble/include/rcpputils/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rcpputils",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcpputils",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcpputils",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrcpputils",
        ],
    }),
)

cc_library(
    name = "rcutils",
    hdrs = glob([
        "opt/ros/humble/include/rcutils/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rcutils",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcutils",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcutils",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrcutils",
        ],
    }),
)

cc_library(
    name = "rmw",
    hdrs = glob([
        "opt/ros/humble/include/rmw/**/*.h",
        "opt/ros/humble/include/rmw/**/*.hpp",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rmw",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrmw",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrmw",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrmw",
        ],
    }),
)

cc_library(
    name = "tracetools",
    hdrs = glob([
        "opt/ros/humble/include/tracetools/**/*.h",
        "opt/ros/humble/include/tracetools/**/*.hpp",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/tracetools",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-ltracetools",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-ltracetools",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-ltracetools",
        ],
    }),
)

cc_library(
    name = "libstatistics_collector",
    hdrs = glob([
        "opt/ros/humble/include/libstatistics_collector/**/*.hpp",
        "opt/ros/humble/include/libstatistics_collector/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/libstatistics_collector",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-llibstatistics_collector",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-llibstatistics_collector",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-llibstatistics_collector",
        ],
    }),
    deps = [":statistics_msgs"],
)

cc_library(
    name = "statistics_msgs",
    hdrs = glob([
        "opt/ros/humble/include/statistics_msgs/**/*.hpp",
        "opt/ros/humble/include/statistics_msgs/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/statistics_msgs",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lstatistics_msgs__rosidl_typesupport_cpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lstatistics_msgs__rosidl_typesupport_cpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lstatistics_msgs__rosidl_typesupport_cpp",
        ],
    }),
    deps = [
        ":std_msgs",
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
    ],
)

cc_library(
    name = "rosgraph_msgs",
    hdrs = glob([
        "opt/ros/humble/include/rosgraph_msgs/**/*.hpp",
        "opt/ros/humble/include/rosgraph_msgs/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rosgraph_msgs",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrosgraph_msgs__rosidl_typesupport_cpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrosgraph_msgs__rosidl_typesupport_cpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrosgraph_msgs__rosidl_typesupport_cpp",
        ],
    }),
    deps = [
        ":std_msgs",
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
    ],
)

cc_library(
    name = "rosidl_runtime_c",
    hdrs = glob([
        "opt/ros/humble/include/rosidl_runtime_c/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rosidl_runtime_c",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrosidl_runtime_c",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrosidl_runtime_c",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrosidl_runtime_c",
        ],
    }),
    deps = [":rosidl_typesupport_interface"],
)

cc_library(
    name = "rosidl_typesupport_interface",
    hdrs = glob([
        "opt/ros/humble/include/rosidl_typesupport_interface/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rosidl_typesupport_interface",
)

cc_library(
    name = "rosidl_runtime_cpp",
    hdrs = glob([
        "opt/ros/humble/include/rosidl_runtime_cpp/**/*.hpp",
        "opt/ros/humble/include/rosidl_runtime_cpp/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rosidl_runtime_cpp",
)

cc_library(
    name = "rosidl_typesupport_c",
    hdrs = glob([
        "opt/ros/humble/include/rosidl_typesupport_c/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rosidl_typesupport_c",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrosidl_typesupport_c",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrosidl_typesupport_c",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrosidl_typesupport_c",
        ],
    }),
)

cc_library(
    name = "rosidl_typesupport_cpp",
    hdrs = glob([
        "opt/ros/humble/include/rosidl_typesupport_cpp/**/*.hpp",
        "opt/ros/humble/include/rosidl_typesupport_cpp/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rosidl_typesupport_cpp",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrosidl_typesupport_cpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrosidl_typesupport_cpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrosidl_typesupport_cpp",
        ],
    }),
)

# ROS2 Action and Lifecycle
cc_library(
    name = "rcl_action",
    hdrs = glob([
        "opt/ros/humble/include/rcl_action/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rcl_action",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_action",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_action",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrcl_action",
        ],
    }),
    deps = [":rcl"],
)

cc_library(
    name = "rclcpp_action",
    hdrs = glob([
        "opt/ros/humble/include/rclcpp_action/**/*.hpp",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rclcpp_action",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrclcpp_action",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrclcpp_action",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrclcpp_action",
        ],
    }),
    deps = [":rclcpp", ":rcl_action"],
)

# ROS2 Common Interfaces (using system-installed headers)
# These are the standard ROS2 message/service definitions
# Note: For full interface support, you may need to use rosidl_generate_interfaces
# or rely on system-installed interface packages

# builtin_interfaces (required by rclcpp)
cc_library(
    name = "builtin_interfaces",
    hdrs = glob([
        "opt/ros/humble/include/builtin_interfaces/**/*.hpp",
        "opt/ros/humble/include/builtin_interfaces/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/builtin_interfaces",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lbuiltin_interfaces__rosidl_typesupport_cpp",
            "-lbuiltin_interfaces__rosidl_typesupport_c",
            "-lbuiltin_interfaces__rosidl_generator_c",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lbuiltin_interfaces__rosidl_typesupport_cpp",
            "-lbuiltin_interfaces__rosidl_typesupport_c",
            "-lbuiltin_interfaces__rosidl_generator_c",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lbuiltin_interfaces__rosidl_typesupport_cpp",
            "-lbuiltin_interfaces__rosidl_typesupport_c",
            "-lbuiltin_interfaces__rosidl_generator_c",
        ],
    }),
    deps = [
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
    ],
)

# Convenience alias
cc_library(
    name = "cpp_builtin_interfaces",
    deps = [":builtin_interfaces"],
)

# rcl_interfaces (required by rclcpp)
cc_library(
    name = "rcl_interfaces",
    hdrs = glob([
        "opt/ros/humble/include/rcl_interfaces/**/*.hpp",
        "opt/ros/humble/include/rcl_interfaces/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/rcl_interfaces",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_interfaces__rosidl_typesupport_cpp",
            "-lrcl_interfaces__rosidl_typesupport_c",
            "-lrcl_interfaces__rosidl_generator_c",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lrcl_interfaces__rosidl_typesupport_cpp",
            "-lrcl_interfaces__rosidl_typesupport_c",
            "-lrcl_interfaces__rosidl_generator_c",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lrcl_interfaces__rosidl_typesupport_cpp",
            "-lrcl_interfaces__rosidl_typesupport_c",
            "-lrcl_interfaces__rosidl_generator_c",
        ],
    }),
    deps = [
        ":builtin_interfaces",
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
    ],
)

# Convenience alias
cc_library(
    name = "cpp_rcl_interfaces",
    deps = [":rcl_interfaces"],
)

# std_msgs
cc_library(
    name = "std_msgs",
    hdrs = glob([
        "opt/ros/humble/include/std_msgs/**/*.hpp",
        "opt/ros/humble/include/std_msgs/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/std_msgs",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lstd_msgs__rosidl_typesupport_cpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lstd_msgs__rosidl_typesupport_cpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lstd_msgs__rosidl_typesupport_cpp",
        ],
    }),
    deps = [
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
    ],
)

# sensor_msgs
cc_library(
    name = "sensor_msgs",
    hdrs = glob([
        "opt/ros/humble/include/sensor_msgs/**/*.hpp",
        "opt/ros/humble/include/sensor_msgs/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/sensor_msgs",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lsensor_msgs__rosidl_typesupport_cpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lsensor_msgs__rosidl_typesupport_cpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lsensor_msgs__rosidl_typesupport_cpp",
        ],
    }),
    deps = [
        ":std_msgs",
        ":geometry_msgs",
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
    ],
)

# geometry_msgs
cc_library(
    name = "geometry_msgs",
    hdrs = glob([
        "opt/ros/humble/include/geometry_msgs/**/*.hpp",
        "opt/ros/humble/include/geometry_msgs/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/geometry_msgs",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lgeometry_msgs__rosidl_typesupport_cpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lgeometry_msgs__rosidl_typesupport_cpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lgeometry_msgs__rosidl_typesupport_cpp",
        ],
    }),
    deps = [
        ":std_msgs",
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
    ],
)

# std_srvs
cc_library(
    name = "std_srvs",
    hdrs = glob([
        "opt/ros/humble/include/std_srvs/**/*.hpp",
        "opt/ros/humble/include/std_srvs/**/*.h",
    ], allow_empty = True),
    strip_include_prefix = "opt/ros/humble/include/std_srvs",
    linkopts = select({
        ":cpu_x86_64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lstd_srvs__rosidl_typesupport_cpp",
        ],
        ":cpu_aarch64": [
            "-L/opt/ros/humble/lib",
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/opt/ros/humble/lib",
            "-lstd_srvs__rosidl_typesupport_cpp",
        ],
        "//conditions:default": [
            "-L/opt/ros/humble/lib",
            "-lstd_srvs__rosidl_typesupport_cpp",
        ],
    }),
    deps = [
        ":rosidl_runtime_cpp",
        ":rosidl_typesupport_cpp",
    ],
)

# Convenience aliases matching rules_ros2 naming
cc_library(
    name = "cpp_std_msgs",
    deps = [":std_msgs"],
)

cc_library(
    name = "cpp_sensor_msgs",
    deps = [":sensor_msgs"],
)

cc_library(
    name = "cpp_geometry_msgs",
    deps = [":geometry_msgs"],
)

cc_library(
    name = "cpp_std_srvs",
    deps = [":std_srvs"],
)
"""
    # Create symlinks (delete first if they exist)
    ctx.delete("usr")
    ctx.delete("opt")
    ctx.symlink("/usr", "usr")
    ctx.symlink("/opt/ros/humble", "opt/ros/humble")
    
    ctx.file("BUILD.bazel", build_content)
    ctx.file("WORKSPACE", 'workspace(name = "{}")'.format(ctx.name))

ros2_libs_repo = repository_rule(
    implementation = _ros2_libs_repo_impl,
    doc = "Creates a repository for local ROS2 libraries by symlinking /opt/ros/humble.",
)

