def _system_libs_repo_impl(ctx):
    """Implementation of the system_libs_repo rule."""
    build_content = """
# AUTOGENERATED by system_libs_repo rule
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# libevdev
cc_library(
    name = "libevdev",
    hdrs = glob(["usr/include/libevdev-1.0/libevdev/*.h"], allow_empty = True),
    includes = ["usr/include/libevdev-1.0", "usr/include"],
    linkopts = ["-levdev"],
)

# boost
cc_library(
    name = "boost_system",
    hdrs = glob([
        "usr/include/boost/system/**/*.hpp",
        "usr/include/boost/system/**/*.h",
    ], allow_empty = True),
    includes = ["usr/include"],
    linkopts = ["-lboost_system"],
)

cc_library(
    name = "boost_thread",
    hdrs = glob([
        "usr/include/boost/thread/**/*.hpp",
        "usr/include/boost/thread/**/*.h",
    ], allow_empty = True),
    includes = ["usr/include"],
    linkopts = ["-lboost_thread"],
)

cc_library(
    name = "boost_asio",
    hdrs = glob([
        "usr/include/boost/asio/**/*.hpp",
        "usr/include/boost/asio/**/*.h",
    ], allow_empty = True),
    includes = ["usr/include"],
    deps = [
        ":boost_system",
        ":boost_thread",
    ],
)

# opencv
cc_library(
    name = "opencv",
    deps = [":videoio", ":features2d", ":flann", ":dnn"],
)

cc_library(
    name = "opencv_headers",
    hdrs = glob([
        "usr/include/opencv4/opencv2/*.hpp",
        "usr/include/opencv4/opencv2/*.h",
    ], allow_empty = True),
    includes = ["usr/include/opencv4"],
)

cc_library(
    name = "core",
    hdrs = glob(["usr/include/opencv4/opencv2/core/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_core"],
    deps = [":opencv_headers"],
)

cc_library(
    name = "highgui",
    hdrs = glob(["usr/include/opencv4/opencv2/highgui/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_highgui"],
    deps = [":core"],
)

cc_library(
    name = "imgproc",
    hdrs = glob(["usr/include/opencv4/opencv2/imgproc/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_imgproc"],
    deps = [":core"],
)

cc_library(
    name = "imgcodecs",
    hdrs = glob(["usr/include/opencv4/opencv2/imgcodecs/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_imgcodecs"],
    deps = [":core"],
)

cc_library(
    name = "videoio",
    hdrs = glob(["usr/include/opencv4/opencv2/videoio/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_videoio"],
    deps = [":highgui", ":imgproc", ":imgcodecs"],
)

cc_library(
    name = "flann",
    hdrs = glob(["usr/include/opencv4/opencv2/flann/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_flann"],
    deps = [":core"],
)

cc_library(
    name = "features2d",
    hdrs = glob(["usr/include/opencv4/opencv2/features2d/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_features2d"],
    deps = [":core", ":flann"],
)

cc_library(
    name = "dnn",
    hdrs = glob(["usr/include/opencv4/opencv2/dnn/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_dnn"],
    deps = [":core", ":imgproc"],
)
"""
    ctx.symlink("/usr", "usr")
    ctx.file("BUILD.bazel", build_content)
    ctx.file("WORKSPACE", 'workspace(name = "{}")'.format(ctx.name))

system_libs_repo = repository_rule(
    implementation = _system_libs_repo_impl,
    doc = "Creates a repository for local system libraries by symlinking /usr.",
) 