def _system_libs_repo_impl(ctx):
    """Implementation of the system_libs_repo rule.
    
    Supports cross-compilation by checking for ROS2_SYSROOT environment variable.
    If ROS2_SYSROOT is set, it will use that as the base path for ROS2 libraries.
    Otherwise, it uses the host system paths (/usr, /opt/ros/humble).
    """
    # Check for sysroot (for cross-compilation)
    # Note: In Starlark, we can't directly access os.environ
    # The sysroot needs to be passed via repository rule attributes or environment
    # For now, we'll use host system paths
    # To use sysroot, set it via repository_rule environment attribute or use multiarch paths
    
    build_content = """
# AUTOGENERATED by system_libs_repo rule
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# Platform selectors for x86_64 vs aarch64
config_setting(
    name = "cpu_x86_64",
    constraint_values = ["@platforms//cpu:x86_64"],
)

config_setting(
    name = "cpu_aarch64",
    constraint_values = ["@platforms//cpu:aarch64"],
)

# opencv
cc_library(
    name = "opencv",
    deps = [":videoio", ":features2d", ":flann", ":dnn"],
)

cc_library(
    name = "opencv_headers",
    hdrs = glob([
        "usr/include/opencv4/opencv2/*.hpp",
        "usr/include/opencv4/opencv2/*.h",
    ], allow_empty = True),
    includes = ["usr/include/opencv4"],
)

cc_library(
    name = "core",
    hdrs = glob(["usr/include/opencv4/opencv2/core/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = select({
        ":cpu_x86_64": [
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/usr/lib/x86_64-linux-gnu",
        ],
        ":cpu_aarch64": [
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/usr/lib/aarch64-linux-gnu",
        ],
        "//conditions:default": [],
    }) + [
        "-lopencv_core",
    ],
    deps = [":opencv_headers"],
)

cc_library(
    name = "highgui",
    hdrs = glob(["usr/include/opencv4/opencv2/highgui/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = select({
        ":cpu_x86_64": [
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/usr/lib/x86_64-linux-gnu",
        ],
        ":cpu_aarch64": [
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/usr/lib/aarch64-linux-gnu",
        ],
        "//conditions:default": [],
    }) + [
        "-lopencv_highgui",
    ],
    deps = [":core"],
)

cc_library(
    name = "imgproc",
    hdrs = glob(["usr/include/opencv4/opencv2/imgproc/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = select({
        ":cpu_x86_64": [
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/usr/lib/x86_64-linux-gnu",
        ],
        ":cpu_aarch64": [
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/usr/lib/aarch64-linux-gnu",
        ],
        "//conditions:default": [],
    }) + [
        "-lopencv_imgproc",
    ],
    deps = [":core"],
)

cc_library(
    name = "imgcodecs",
    hdrs = glob(["usr/include/opencv4/opencv2/imgcodecs/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = select({
        ":cpu_x86_64": [
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/usr/lib/x86_64-linux-gnu",
        ],
        ":cpu_aarch64": [
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/usr/lib/aarch64-linux-gnu",
        ],
        "//conditions:default": [],
    }) + [
        "-lopencv_imgcodecs",
    ],
    deps = [":core"],
)

cc_library(
    name = "videoio",
    hdrs = glob(["usr/include/opencv4/opencv2/videoio/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = select({
        ":cpu_x86_64": [
            "-L/usr/lib/x86_64-linux-gnu",
            "-Wl,-rpath,/usr/lib/x86_64-linux-gnu",
        ],
        ":cpu_aarch64": [
            "-L/usr/lib/aarch64-linux-gnu",
            "-Wl,-rpath,/usr/lib/aarch64-linux-gnu",
        ],
        "//conditions:default": [],
    }) + [
        "-lopencv_videoio",
    ],
    deps = [":highgui", ":imgproc", ":imgcodecs"],
)

cc_library(
    name = "flann",
    hdrs = glob(["usr/include/opencv4/opencv2/flann/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_flann"],
    deps = [":core"],
)

cc_library(
    name = "features2d",
    hdrs = glob(["usr/include/opencv4/opencv2/features2d/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_features2d"],
    deps = [":core", ":flann"],
)

cc_library(
    name = "dnn",
    hdrs = glob(["usr/include/opencv4/opencv2/dnn/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_dnn"],
    deps = [":core", ":imgproc"],
)

# libevdev for Xbox controller
cc_library(
    name = "libevdev",
    hdrs = glob(["usr/include/libevdev-1.0/libevdev/*.h"], allow_empty = True),
    includes = ["usr/include/libevdev-1.0"],
    linkopts = ["-levdev"],
)

# Qt6 C++ libraries
cc_library(
    name = "qt6_core",
    hdrs = glob([
        "usr/include/x86_64-linux-gnu/qt6/**",
    ], allow_empty = True),
    includes = [
        "usr/include/x86_64-linux-gnu/qt6",
        "usr/include/x86_64-linux-gnu/qt6/QtCore",
    ],
    linkopts = ["-lQt6Core"],
)

cc_library(
    name = "qt6_gui",
    hdrs = glob([
        "usr/include/x86_64-linux-gnu/qt6/**",
    ], allow_empty = True),
    includes = [
        "usr/include/x86_64-linux-gnu/qt6",
        "usr/include/x86_64-linux-gnu/qt6/QtGui",
        "usr/include/x86_64-linux-gnu/qt6/QtCore",
    ],
    linkopts = ["-lQt6Gui"],
    deps = [":qt6_core"],
)

cc_library(
    name = "qt6_widgets",
    hdrs = glob([
        "usr/include/x86_64-linux-gnu/qt6/**",
    ], allow_empty = True),
    includes = [
        "usr/include/x86_64-linux-gnu/qt6",
        "usr/include/x86_64-linux-gnu/qt6/QtWidgets",
        "usr/include/x86_64-linux-gnu/qt6/QtGui",
        "usr/include/x86_64-linux-gnu/qt6/QtCore",
    ],
    linkopts = ["-lQt6Widgets"],
    deps = [":qt6_gui"],
)

# Convenience target for all Qt6 libraries
cc_library(
    name = "qt6",
    deps = [":qt6_core", ":qt6_gui", ":qt6_widgets"],
)

# Qt6 MOC tool
cc_binary(
    name = "qt6_moc",
    srcs = [],
    data = ["usr/bin/moc"],
    visibility = ["//visibility:public"],
)
"""
    # Create symlinks (delete first if they exist)
    ctx.delete("usr")
    ctx.delete("opt")
    ctx.symlink("/usr", "usr")
    ctx.symlink("/opt/ros/humble", "opt/ros/humble")
    
    ctx.file("BUILD.bazel", build_content)
    ctx.file("WORKSPACE", 'workspace(name = "{}")'.format(ctx.name))

system_libs_repo = repository_rule(
    implementation = _system_libs_repo_impl,
    doc = "Creates a repository for local system libraries by symlinking /usr and /opt/ros/humble.",
)
