def _system_libs_repo_impl(ctx):
    """Implementation of the system_libs_repo rule."""
    build_content = """
# AUTOGENERATED by system_libs_repo rule
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# ROS2 libraries
cc_library(
    name = "rclcpp",
    hdrs = glob([
        "opt/ros/jazzy/include/rclcpp/**/*.hpp",
        "opt/ros/jazzy/include/rclcpp/**/*.h",
    ], allow_empty = True),
    includes = ["opt/ros/jazzy/include"],
    linkopts = ["-lrclcpp"],
)



cc_library(
    name = "rosidl_typesupport_cpp",
    hdrs = glob([
        "opt/ros/jazzy/include/rosidl_typesupport_cpp/**/*.hpp",
        "opt/ros/jazzy/include/rosidl_typesupport_cpp/**/*.h",
    ], allow_empty = True),
    includes = ["opt/ros/jazzy/include"],
    linkopts = ["-lrosidl_typesupport_cpp"],
)

# opencv
cc_library(
    name = "opencv",
    deps = [":videoio", ":features2d", ":flann", ":dnn"],
)

cc_library(
    name = "opencv_headers",
    hdrs = glob([
        "usr/include/opencv4/opencv2/*.hpp",
        "usr/include/opencv4/opencv2/*.h",
    ], allow_empty = True),
    includes = ["usr/include/opencv4"],
)

cc_library(
    name = "core",
    hdrs = glob(["usr/include/opencv4/opencv2/core/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_core"],
    deps = [":opencv_headers"],
)

cc_library(
    name = "highgui",
    hdrs = glob(["usr/include/opencv4/opencv2/highgui/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_highgui"],
    deps = [":core"],
)

cc_library(
    name = "imgproc",
    hdrs = glob(["usr/include/opencv4/opencv2/imgproc/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_imgproc"],
    deps = [":core"],
)

cc_library(
    name = "imgcodecs",
    hdrs = glob(["usr/include/opencv4/opencv2/imgcodecs/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_imgcodecs"],
    deps = [":core"],
)

cc_library(
    name = "videoio",
    hdrs = glob(["usr/include/opencv4/opencv2/videoio/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_videoio"],
    deps = [":highgui", ":imgproc", ":imgcodecs"],
)

cc_library(
    name = "flann",
    hdrs = glob(["usr/include/opencv4/opencv2/flann/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_flann"],
    deps = [":core"],
)

cc_library(
    name = "features2d",
    hdrs = glob(["usr/include/opencv4/opencv2/features2d/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_features2d"],
    deps = [":core", ":flann"],
)

cc_library(
    name = "dnn",
    hdrs = glob(["usr/include/opencv4/opencv2/dnn/**/*.h*"], allow_empty = True),
    includes = ["usr/include/opencv4"],
    linkopts = ["-lopencv_dnn"],
    deps = [":core", ":imgproc"],
)

# libevdev for Xbox controller
cc_library(
    name = "libevdev",
    hdrs = glob(["usr/include/libevdev-1.0/libevdev/*.h"], allow_empty = True),
    includes = ["usr/include/libevdev-1.0"],
    linkopts = ["-levdev"],
)
"""
    ctx.symlink("/usr", "usr")
    ctx.symlink("/opt/ros/jazzy", "opt/ros/jazzy")
    ctx.file("BUILD.bazel", build_content)
    ctx.file("WORKSPACE", 'workspace(name = "{}")'.format(ctx.name))

system_libs_repo = repository_rule(
    implementation = _system_libs_repo_impl,
    doc = "Creates a repository for local system libraries by symlinking /usr and /opt/ros/jazzy.",
) 