syntax = "proto3";

import "robot/actuation/proto/actuation_packet.proto";
import "robot/perception/proto/perception_packet.proto";

package robot.nexus;

message NexusActionPacket {
    uint64 timestamp = 1;
    string action_id = 2;
    oneof action_packet_type {
        robot.actuation.STS3215ActuationPayload sts3215_action = 3;
    }
}

message NexusPerceptionPacket {
    uint64 timestamp = 1;
    string perception_id = 2;
    oneof perception_packet_type {
        robot.perception.CameraPerceptionPayload camera_perception = 3;
        robot.perception.EncoderPerceptionPayload encoder_perception = 4;
    }
}

// A message to pass to the AI layer for model input.
message NexusModelInputPacket {
    uint64 timestamp = 1;
    repeated NexusPerceptionPacket perception_packets = 2;

    // This field provides a command or goal for the AI model.
    // It's designed to be generic to support different types of policies.
    oneof command {
        float target_return_to_go = 3; // For Decision Transformer style models
        string text_command = 4;       // For future language-conditioned models
    }
}

// A message that is the output from the AI layer.
message NexusModelOutputPacket {
    uint64 timestamp = 1;
    repeated NexusActionPacket action_packets = 3;
}