load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "frame_transport",
    hdrs = ["frame_transport.h"],
    visibility = ["//visibility:public"],
    deps = ["//robot/comm/interfaces:message_transport"],
)
