load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "action_interface",
    hdrs = ["action_interface.h"],
    deps = [
        "@glog//:glog",
    ],
    visibility = ["//visibility:public"],
)
