syntax = "proto3";

import "robot/comm/proto/comm.proto";

package robot.perception;

enum PerceptionType {
    PERCEPTION_INVALID = 0;
    CAMERA = 1;
    ENCODER = 2;
    LIDAR = 3;
    RADAR = 4;
    HID = 5; // Human Interface Device
}

enum EncoderDataMode {
    ENCODER_DATA_MODE_INVALID = 0;
    ENCODER_DATA_MODE_RAW = 1;
    ENCODER_DATA_MODE_NORMALIZED_ZERO_TO_ONE = 2;
    ENCODER_DATA_MODE_NORMALIZED_MINUS_ONE_TO_ONE = 3;
    ENCODER_DATA_MODE_NORMALIZED_RADIAN = 4;
}

enum CameraType {
    CAMERA_INVLAID = 0;
    OPENCV = 1;
}

enum EncoderType {
    ENCODER_INVLAID = 0;
    STS3215_ENCODER = 1;
}

enum LidarType {
    LIDAR_INVLAID = 0;
}

enum RadarType {
    RADAR_INVLAID = 0;
}

enum HidType {
    HID_INVLAID = 0;
}

message Camera {
    string camera_name = 1;
    uint64 id = 2;
    CameraType camera_type = 3;
    robot.comm.Comm comm = 4;
    oneof camera_config {
        OpenCvConfig opencv_config = 6;
    }
}

message Encoder {
    string encoder_name = 1;
    uint64 id = 2;
    EncoderType encoder_type = 3;
    robot.comm.Comm comm = 4;
    uint32 operational_lower_limit = 5;
    uint32 operational_upper_limit = 6;
    EncoderDataMode encoder_data_mode = 7;
    oneof encoder_config {
        Sts3215EncoderConfig sts3215_encoder_config = 9;
    }
}

message OpenCvConfig {
    uint64 id = 1;
    uint32 width = 2;
    uint32 height = 3;
    uint32 fps = 4;
}

message Sts3215EncoderConfig {
    uint64 servo_id = 1;    
}

message SinglePerception {
    uint32 node_id = 1;
    string publish_topic = 2;
    uint32 publish_rate_hz = 3;
    PerceptionType perception_type = 4;
    oneof perception_data {
        Camera camera = 5;
        Encoder encoder = 6;
    }
}

message Perception {
    repeated SinglePerception single_perceptions = 1;
}
