general {
  operation_mode: MODE_SIMULATION
  robot_type: ROBOT_TYPE_MANIPULATOR_ARM
  name: "so100"
}
simulation {
  model_path: "simulation/models/so_arm100/so_arm100_scene.xml"
  mode: MODE_PASSIVE
  passive {
    trajectory_path: "simulation/models/so_arm100/trajectories/example_trajectory.csv"
    speed: 1.0
  }
}
