general {
  operation_mode: MODE_TRAINING
  robot_type: ROBOT_TYPE_MANIPULATOR_ARM
  name: "so100"
}
ai {
  training {
    environment: TRAINING_ENV_REAL
    method: TRAINING_METHOD_IMITATION
    imitation {
      dataset_path: "/tmp/Joshua/data/sample_recordings"
      base_model: "lerobot/act_so100"
      epochs: 100
      learning_rate: 0.0001
      save_path: "so100_finetuned"
      batch_size: 32
    }
  }
}
