syntax = "proto3";

package ai.models;

import "ai/models/random_noise/random_noise_config.proto";
import "ai/models/smolvla/smolvla_config.proto";
import "ros2/proto/node.proto";
import "ros2/proto/ros2_data_type.proto";

enum ModelType {
  MODEL_TYPE_INVALID = 0;
  RANDOM_NOISE = 1;
  SMOLVLA = 2;
  // Add other model types here.
}

message SingleModel {
  ModelType model_type = 1;
  string pretrained_model_path = 2;
  ros2.node.Node node = 3;

  oneof model_config {
    RandomNoiseConfig random_noise_config = 4;
    SmolVLAConfig smolvla_config = 5;
    // Add other model configs here.
  }
}

message Model {
  repeated SingleModel single_models = 1;
}
