syntax = "proto3";

package ai.model;

import "ros2/proto/node.proto";

enum Ros2DataType {
  DATA_TYPE_INVALID = 0;
  // std_msgs
  FLOAT32 = 1;
  FLOAT64 = 2;
  INT32 = 3;
  BOOL = 4;
  STRING = 5;
  INT8 = 6;
  INT16 = 7;
  INT64 = 8;
  UINT8 = 9;
  UINT16 = 10;
  UINT32 = 11;
  UINT64 = 12;
  BYTE = 13;
  CHAR = 14;
  EMPTY = 15;
  COLOR_RGBA = 16;
  HEADER = 17;
  FLOAT32_MULTI_ARRAY = 18;
  FLOAT64_MULTI_ARRAY = 19;
  INT8_MULTI_ARRAY = 20;
  INT16_MULTI_ARRAY = 21;
  INT32_MULTI_ARRAY = 22;
  INT64_MULTI_ARRAY = 23;
  UINT8_MULTI_ARRAY = 24;
  UINT16_MULTI_ARRAY = 25;
  UINT32_MULTI_ARRAY = 26;
  UINT64_MULTI_ARRAY = 27;
  MULTI_ARRAY_DIMENSION = 28;
  MULTI_ARRAY_LAYOUT = 29;
  // sensor_msgs
  IMAGE = 30;
  LASER_SCAN = 31;
  IMU = 32;
  POINTCLOUD2 = 33;
  BATTERY_STATE = 34;
  CAMERA_INFO = 35;
  CHANNEL_FLOAT32 = 36;
  COMPRESSED_IMAGE = 37;
  FLUID_PRESSURE = 38;
  ILLUMINANCE = 39;
  JOINT_STATE = 40;
  JOY = 41;
  JOY_FEEDBACK = 42;
  JOY_FEEDBACK_ARRAY = 43;
  LASER_ECHO = 44;
  MAGNETIC_FIELD = 45;
  MULTI_DOF_JOINT_STATE = 46;
  MULTI_ECHO_LASER_SCAN = 47;
  NAV_SAT_FIX = 48;
  NAV_SAT_STATUS = 49;
  POINT_CLOUD = 50;
  POINT_FIELD = 51;
  RANGE = 52;
  REGION_OF_INTEREST = 53;
  RELATIVE_HUMIDITY = 54;
  TEMPERATURE = 55;
  TIME_REFERENCE = 56;
  // nav_msgs
  ODOMETRY = 57;
  GRID_CELLS = 58;
  MAP_META_DATA = 59;
  OCCUPANCY_GRID = 60;
  PATH = 61;
  // geometry_msgs
  TWIST = 62;
  POSE = 63;
  ACCEL = 64;
  ACCEL_STAMPED = 65;
  ACCEL_WITH_COVARIANCE = 66;
  ACCEL_WITH_COVARIANCE_STAMPED = 67;
  INERTIA = 68;
  INERTIA_STAMPED = 69;
  POINT = 70;
  POINT32 = 71;
  POINT_STAMPED = 72;
  POLYGON = 73;
  POLYGON_STAMPED = 74;
  POSE2D = 75;
  POSE_ARRAY = 76;
  POSE_STAMPED = 77;
  POSE_WITH_COVARIANCE = 78;
  POSE_WITH_COVARIANCE_STAMPED = 79;
  QUATERNION = 80;
  QUATERNION_STAMPED = 81;
  TRANSFORM = 82;
  TRANSFORM_STAMPED = 83;
  TWIST_STAMPED = 84;
  TWIST_WITH_COVARIANCE = 85;
  TWIST_WITH_COVARIANCE_STAMPED = 86;
  VECTOR3 = 87;
  VECTOR3_STAMPED = 88;
  WRENCH = 89;
  WRENCH_STAMPED = 90;
  // tf2_msgs
  TF_MESSAGE = 91;
}

message SingleModel {
  string policy_name = 1;
  string pretrained_model_path = 2;
  ros2.node.Node node = 3;
  repeated Subscription subscriptions = 4;
  repeated Publisher pubishers = 5;
  oneof policy_config {
    ExamplePolicyConfig example_policy_config = 6;
  }
}

message Publisher {
  Ros2DataType ros2_data_type = 1;
  string topic = 2;
}

message Subscription {
  Ros2DataType ros2_data_type = 1;
  string topic = 2;
}

message ExamplePolicyConfig {
  int32 hidden_size = 1;
  int32 n_layer = 2;
  int32 n_head = 3;
  string activation_function = 4;
  double dropout = 5;
  int32 n_inner = 6;
  int32 context_length = 7;
  int32 vision_embedding_dim = 8;
}

message Model {
  repeated SingleModel single_model = 1;
}
